name: TeslaRIS Frontend CI

on:
    push:
    pull_request:
        branches: ["main"]
        # Don't run if PR is only updating static documentation
        paths-ignore:
            - "**/*.md"
            - "**/*.txt"

jobs:
    build:
        runs-on: ubuntu-latest

    steps:
        - name: Checkout Git repository
          uses: actions/checkout@v3

        - name: Setup Node.js environment
          uses: actions/setup-node@v3
          with:
              node-version: "16"

        - name: Cache node_modules
          uses: actions/cache@v3
          with:
              path: ~/.npm
              key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
              restore-keys: ${{ runner.os }}-node-

        - name: Install package dependencies
          run: npm ci

        - name: Build dist files
          run: npm run build

        - name: Lint project
          run: npm run lint
